## PROJECT 1
+ This project deals with the analysing and predicting the price range of mobiles based on the given data.
+ In this project the model created and algorithms used are LOGISTIC REGRESSION, KNN CLASSIFICATION, SUPPORT VECTOR MACHINE(SVM).

In [1]:
import pandas as pd
import numpy as np

In [2]:
d = pd.read_csv("mobile_price_range_data.csv")
d

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [3]:
d.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

## REMOVING NULL VALUES

In [4]:
d.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [5]:
d.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

## SPLITTING THE DATA INTO TRAIN AND TEST DATA

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
d = pd.read_csv("mobile_price_range_data.csv")

In [8]:
X = d.iloc[:,:-1]
Y = d.iloc[:,-1]

In [9]:
# splitting the dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.50,random_state=0)

In [10]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(1000, 20)
(1000, 20)
(1000,)
(1000,)


In [11]:
X_train.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
103            1939     1          2.8         1   0       1          55   
1638            667     0          2.6         1   3       0           8   
60             1484     0          3.0         0   3       0          12   
784            1892     1          0.7         0   5       0          47   
1084           1836     0          1.1         1   0       0          14   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
103     0.6        199        4  10        320       520  1047    14    10   
1638    0.8        185        1   7       1015      1947  2528    11     8   
60      0.6        134        3   5        916       969  1457    14     4   
784     0.4        110        4  10       1399      1564  2172    17    14   
1084    0.7        104        5   1        168      1068  2469    18     6   

      talk_time  three_g  touch_screen  wifi  
103          18        1             1     0  
1638          8        0             1     0  
60           20        1             1     0  
784           3        1             1     1  
1084          7        1             1     1

In [12]:
Y_train.head()

103     0
1638    2
60      1
784     2
1084    2
Name: price_range, dtype: int64

In [13]:
X_test.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
405            1454     1          0.5         1   1       0          34   
1190           1092     1          0.5         1  10       0          11   
1132           1524     1          1.8         1   0       0          10   
731            1807     1          2.1         0   2       0          49   
1754           1086     1          1.7         1   0       1          43   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
405     0.7         83        4   3        250      1033  3419     7     5   
1190    0.5        167        3  14        468       571   737    14     4   
1132    0.6        174        4   1        154       550  2678    16     5   
731     0.8        125        1  10        337      1384  1906    17    13   
1754    0.2        111        6   1         56      1150  3285    11     5   

      talk_time  three_g  touch_screen  wifi  
405           5        1             1     0  
1190         11        0             1     0  
1132         13        1             0     1  
731          13        0             1     1  
1754         17        1             1     0

In [14]:
Y_test.head()

405     3
1190    0
1132    2
731     2
1754    2
Name: price_range, dtype: int64

## A) LOGISTIC REGRESSION

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model = LogisticRegression()
model.fit(X_train,Y_train)

C:\Users\SURYA\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
print('Training score', model.score(X_train, Y_train))
print('Testing score', model.score(X_test, Y_test))

Training score 0.629
Testing score 0.64


In [18]:
pred1 =model.predict(X_test)
pred1

array([3, 0, 2, 1, 3, 0, 0, 2, 2, 2, 1, 3, 1, 1, 2, 0, 3, 2, 2, 1, 1, 0,
       3, 2, 1, 2, 3, 1, 3, 1, 2, 0, 1, 1, 2, 3, 0, 0, 3, 2, 3, 3, 3, 3,
       2, 2, 0, 1, 3, 1, 1, 2, 0, 3, 0, 3, 3, 1, 0, 3, 3, 2, 2, 1, 1, 3,
       3, 3, 2, 2, 3, 2, 1, 0, 1, 3, 3, 1, 1, 1, 3, 2, 3, 0, 0, 0, 1, 0,
       1, 3, 2, 2, 1, 1, 0, 3, 2, 3, 0, 2, 1, 2, 2, 0, 3, 2, 3, 2, 3, 3,
       2, 0, 0, 2, 3, 3, 1, 0, 1, 0, 0, 3, 2, 2, 1, 2, 1, 1, 0, 3, 1, 3,
       3, 2, 3, 3, 3, 3, 0, 1, 1, 3, 2, 3, 1, 3, 0, 0, 2, 0, 1, 1, 1, 1,
       3, 0, 0, 3, 1, 3, 2, 2, 2, 1, 3, 3, 3, 3, 1, 1, 3, 2, 1, 3, 3, 0,
       1, 1, 3, 0, 3, 1, 0, 1, 2, 1, 2, 0, 3, 3, 3, 3, 1, 1, 2, 1, 0, 3,
       2, 0, 3, 3, 3, 0, 1, 3, 2, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2,
       2, 3, 0, 0, 3, 3, 2, 3, 0, 3, 1, 0, 0, 3, 2, 0, 2, 2, 0, 0, 0, 3,
       3, 2, 0, 0, 2, 3, 3, 1, 3, 0, 2, 1, 1, 0, 1, 2, 3, 2, 1, 0, 1, 3,
       3, 3, 2, 3, 3, 2, 1, 2, 2, 2, 1, 3, 2, 2, 2, 1, 0, 2, 1, 0, 0, 0,
       1, 3, 3, 3, 0, 1, 2, 0, 2, 2, 3, 0, 1, 0, 1,

## B) KNN CLASSIFIER

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [20]:
knn = KNeighborsClassifier(n_neighbors = 11)
knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=11)

In [21]:
print('Training score', knn.score(X_train, Y_train))
print('Testing score', knn.score(X_test, Y_test))

Training score 0.937
Testing score 0.921


In [22]:
pred2 = knn.predict(X_test)
pred2

array([3, 0, 2, 1, 3, 0, 0, 3, 3, 1, 0, 3, 0, 2, 3, 0, 3, 2, 2, 1, 0, 0,
       3, 1, 2, 2, 3, 1, 3, 1, 1, 0, 2, 0, 1, 3, 0, 0, 3, 3, 3, 1, 3, 3,
       1, 3, 0, 1, 3, 1, 1, 3, 0, 3, 0, 3, 2, 2, 0, 3, 3, 1, 3, 2, 1, 2,
       3, 2, 2, 2, 3, 2, 1, 0, 1, 3, 2, 2, 1, 2, 3, 3, 3, 0, 0, 0, 2, 0,
       2, 3, 1, 2, 2, 1, 0, 3, 2, 3, 0, 3, 1, 1, 3, 1, 3, 2, 2, 3, 2, 3,
       3, 0, 0, 1, 2, 3, 0, 0, 1, 0, 0, 3, 2, 2, 1, 2, 1, 1, 0, 2, 1, 3,
       3, 3, 3, 3, 3, 2, 0, 1, 1, 2, 1, 3, 0, 3, 0, 0, 2, 0, 1, 1, 1, 1,
       3, 0, 0, 3, 1, 3, 2, 1, 3, 1, 2, 3, 3, 2, 1, 0, 3, 1, 2, 3, 3, 0,
       2, 2, 3, 0, 2, 1, 0, 1, 2, 1, 2, 0, 3, 3, 1, 1, 0, 2, 3, 0, 1, 2,
       2, 0, 3, 3, 3, 1, 2, 3, 3, 3, 1, 0, 0, 2, 3, 3, 0, 0, 1, 3, 1, 3,
       3, 3, 0, 0, 2, 2, 3, 1, 0, 2, 0, 0, 0, 3, 3, 0, 2, 2, 1, 1, 0, 3,
       3, 3, 0, 0, 1, 3, 3, 1, 3, 0, 3, 1, 1, 0, 2, 3, 3, 2, 0, 0, 1, 2,
       3, 2, 2, 3, 1, 1, 0, 3, 3, 2, 1, 3, 3, 2, 2, 1, 0, 2, 2, 1, 0, 0,
       2, 2, 2, 2, 0, 1, 3, 0, 1, 2, 3, 0, 2, 0, 1,

## C) SVM CLASSIFIER

In [23]:
from sklearn.datasets import make_classification
from sklearn import svm
import matplotlib.pyplot as plt

In [24]:
classes = 4
X , t = make_classification(100,5,n_classes = classes, random_state = 40, n_informative = 2, n_clusters_per_class = 1)
svm_model = svm.SVC(kernel = "linear", random_state = 0 ,C = 0.50)
svm_model.fit(X_train,Y_train)

SVC(C=0.5, kernel='linear', random_state=0)

In [25]:
pred3 = svm_model.predict(X_test)
pred4 = svm_model.predict(X_train)
print(pred3)
print(pred4)

[3 0 2 2 2 0 0 3 3 1 1 3 0 2 3 0 3 2 2 1 0 0 3 1 2 2 3 1 3 1 1 0 2 0 1 3 0
 0 3 3 2 1 3 3 1 3 0 1 3 1 1 3 0 3 0 2 2 2 0 3 3 1 3 2 1 2 3 2 2 2 3 2 1 0
 1 3 2 2 1 2 3 3 3 0 0 0 2 1 2 3 1 2 2 1 0 3 3 3 0 3 1 1 3 1 3 2 2 3 2 3 3
 0 0 1 3 3 0 0 1 0 0 3 2 2 1 1 1 1 0 2 1 3 3 3 3 3 3 2 0 1 1 2 1 3 1 3 0 0
 2 0 1 1 1 1 3 0 0 3 1 3 2 1 3 1 2 3 3 2 1 0 3 1 2 3 3 0 2 2 3 0 2 1 0 1 2
 1 2 0 3 3 1 1 0 2 3 0 1 3 2 0 3 3 3 1 2 3 3 3 0 0 0 2 3 3 0 0 1 3 2 3 3 3
 0 0 2 2 3 1 0 2 0 0 0 3 2 0 2 2 1 1 0 2 3 3 0 0 1 3 3 2 3 0 3 1 1 0 2 3 3
 2 0 0 1 2 3 2 2 3 2 1 0 3 3 2 1 3 2 2 2 1 0 2 2 1 0 0 2 2 2 2 0 1 3 0 2 2
 3 0 2 0 1 1 3 0 0 1 3 1 2 0 2 0 3 0 3 3 2 3 1 2 2 1 1 1 0 1 0 3 1 0 3 0 0
 1 3 0 3 1 2 0 1 3 0 2 2 1 2 1 1 0 2 0 0 3 1 2 3 2 2 0 3 2 2 1 3 2 3 3 3 0
 2 0 3 0 1 1 2 2 1 3 1 2 0 1 2 3 0 0 1 3 0 3 0 2 2 1 1 0 2 0 0 1 3 0 3 3 0
 2 1 3 1 1 3 2 0 3 2 2 0 0 3 0 1 1 1 3 2 3 2 0 3 0 0 1 3 0 0 3 2 2 2 3 0 0
 1 2 1 2 0 3 3 0 3 3 0 2 2 1 0 2 2 1 3 2 2 0 2 0 3 3 2 1 0 3 1 2 0 0 1 3 0
 3 0 0 1 2 0 1 3 0 2 2 1 

## COMPUTE CONFUSION MATRIX AND CLASSIFICATION REPORTS OF MODELS

In [26]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix , classification_report

In [27]:
cm_m1 = confusion_matrix(Y_test,pred1)
print(cm_m1)
print(classification_report(Y_test,pred1))

[[196  55   3   0]
 [ 27 133  62  15]
 [  0  65 121  64]
 [  0   1  68 190]]
              precision    recall  f1-score   support

           0       0.88      0.77      0.82       254
           1       0.52      0.56      0.54       237
           2       0.48      0.48      0.48       250
           3       0.71      0.73      0.72       259

    accuracy                           0.64      1000
   macro avg       0.65      0.64      0.64      1000
weighted avg       0.65      0.64      0.64      1000



In [28]:
cm_m2 = confusion_matrix(Y_test,pred2)
print(cm_m2)
print(classification_report(Y_test,pred2))

[[250   4   0   0]
 [ 10 216  11   0]
 [  0  23 210  17]
 [  0   0  14 245]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       254
           1       0.89      0.91      0.90       237
           2       0.89      0.84      0.87       250
           3       0.94      0.95      0.94       259

    accuracy                           0.92      1000
   macro avg       0.92      0.92      0.92      1000
weighted avg       0.92      0.92      0.92      1000



In [29]:
cm_m3 = confusion_matrix(Y_test,pred3)
print(cm_m3)
print(classification_report(Y_test,pred3))

[[254   0   0   0]
 [  5 229   3   0]
 [  0   4 239   7]
 [  0   0   5 254]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       254
           1       0.98      0.97      0.97       237
           2       0.97      0.96      0.96       250
           3       0.97      0.98      0.98       259

    accuracy                           0.98      1000
   macro avg       0.98      0.98      0.98      1000
weighted avg       0.98      0.98      0.98      1000



In [30]:
cm_m4 = confusion_matrix(Y_test,pred4)
print(cm_m4)
print(classification_report(Y_test,pred4))

[[56 66 64 68]
 [66 60 53 58]
 [58 63 67 62]
 [66 74 66 53]]
              precision    recall  f1-score   support

           0       0.23      0.22      0.22       254
           1       0.23      0.25      0.24       237
           2       0.27      0.27      0.27       250
           3       0.22      0.20      0.21       259

    accuracy                           0.24      1000
   macro avg       0.24      0.24      0.24      1000
weighted avg       0.24      0.24      0.24      1000

